export const FETCH_IMAGES_REQUEST = "FETCH_IMAGES_REQUEST";
export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_ERROR = "FETCH_IMAGES_ERROR";

export const SAVE_SEARCH = "SAVE_SEARCH";
export const SHOW_SEARCH = "SHOW_SEARCH";

export const ON_SEARCH_KEY_UP = "ON_SEARCH_KEY_UP";

export const TOGGLE_AND_OR = "TOGGLE_AND_OR";
